Loading python/3.10.4-gcc-8.3.0-ovkjwzd
  Loading requirement: gettext/0.20.2-gcc-8.3.0-uyhs3hu
    readline/8.0-gcc-8.3.0-byomgzx ncurses/6.2-gcc-8.3.0-mkdhl6r
    openssl/1.1.1g-gcc-8.3.0-yzmrseq sqlite/3.31.1-gcc-8.3.0-lvpives
    gdbm/1.18.1-gcc-8.3.0-uwdxv2w zlib/1.2.11-gcc-8.3.0-645472e
    bzip2/1.0.8-gcc-8.3.0-6yutpiz xz/5.2.5-gcc-8.3.0-okaxlo7
    expat/2.2.9-gcc-8.3.0-2royrdp libffi/3.3-gcc-8.3.0-dfl5uuc
    libuuid/1.0.3-gcc-8.3.0-uitghii
/bin/sh: /cvmfs/software.metacentrum.cz/spack1/software/ncurses/linux-debian10-x86_64/6.2-gcc-mkdhl6/lib/libtinfo.so.6: no version information available (required by /bin/sh)
/bin/sh: /cvmfs/software.metacentrum.cz/spack1/software/ncurses/linux-debian10-x86_64/6.2-gcc-mkdhl6/lib/libtinfo.so.6: no version information available (required by /bin/sh)
modules added
venv running
üéôÔ∏è Transcribing /auto/vestec1-elixir/home/sajdokova/Rag/data/npfl138-2324-07-english.mp4...
Traceback (most recent call last):
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/bin/whisper", line 8, in <module>
    sys.exit(cli())
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/transcribe.py", line 595, in cli
    model = load_model(model_name, device=device, download_root=model_dir)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 137, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 55, in _download
    os.makedirs(root, exist_ok=True)
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.10.4-gcc-ovkjwz/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
‚úÖ Saved: /auto/vestec1-elixir/home/sajdokova/Rag/data/transcripts/npfl138-2324-07-english.txt
üéôÔ∏è Transcribing /auto/vestec1-elixir/home/sajdokova/Rag/data/npfl138-2324-08-english.mp4...
Traceback (most recent call last):
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/bin/whisper", line 8, in <module>
    sys.exit(cli())
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/transcribe.py", line 595, in cli
    model = load_model(model_name, device=device, download_root=model_dir)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 137, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 55, in _download
    os.makedirs(root, exist_ok=True)
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.10.4-gcc-ovkjwz/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
‚úÖ Saved: /auto/vestec1-elixir/home/sajdokova/Rag/data/transcripts/npfl138-2324-08-english.txt
üéôÔ∏è Transcribing /auto/vestec1-elixir/home/sajdokova/Rag/data/npfl138-2324-09-english.mp4...
Traceback (most recent call last):
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/bin/whisper", line 8, in <module>
    sys.exit(cli())
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/transcribe.py", line 595, in cli
    model = load_model(model_name, device=device, download_root=model_dir)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 137, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/storage/praha1/home/sajdokova/.virtualenvs/whisper_env/lib/python3.10/site-packages/whisper/__init__.py", line 55, in _download
    os.makedirs(root, exist_ok=True)
  File "/cvmfs/software.metacentrum.cz/spack1/software/python/linux-debian10-x86_64/3.10.4-gcc-ovkjwz/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
‚úÖ Saved: /auto/vestec1-elixir/home/sajdokova/Rag/data/transcripts/npfl138-2324-09-english.txt
